services:
  - type: web
    name: tooldesks-live-streamer
    env: python
    buildCommand: apt-get update && apt-get install -y ffmpeg && pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
